### PR TITLE
feat: export `createFuture` and friends

### PR DESCRIPTION
**Pull request by neurosnap**
I think since a future is a promise-like structure that integrates with effection externally people are going to want to use it.

### CODE REVIEW

**Comment by cowboyd** [comment]
I'm a bit hesitant to do this because the main purpose of `Future` is to be an adapter from `Computation` -> `Operation`, and `Task` -> `Promise`. While `v2` required the explicit use of `Future` quite a bit, a glance at the `v3` codebase shows that never actually create use `Future` for anything other than to surface the result of a `Computation` as an `Operation`.

In every case I can think of, `action()` is better, since it passes you its `resolve()/reject()` pairing, but it is implicitly bound to a parent frame. I'd like to keep the API surface you need to learn (and that we document) as small as possible.

Is there a use-case you have in mind?

**Comment by neurosnap** [comment]
My immediate need is for testing purposes.  I wanted a `defer` promise for writing tests.  I can use `action()` but then I'm reinventing parts of `Future` -- which is fine.

**Comment by cowboyd** [comment]
> My immediate need is for testing purposes. I wanted a `defer` promise for writing tests. I can use `action()` but then I'm reinventing parts of `Future` -- which is fine.

Setting the timing for test cases isn't something I'd thought of. I guess we can make up for it in documentation? As in "95% of the time, what you really want is an action, so really try to make that work, and if it doesn't go ahead and use future"

**Review by cowboyd — APPROVED** [review]

**Comment by neurosnap** [comment]
Closing for now, we can revisit again later if there's more need for a Future in dev-land

**Pull request closed without merging**
